### ISSUE TITLE
Default local connection

### ISSUE THREAD

**Issue by ripleymj** [ripleymj/uugvm-ansible#17]
Add  connection: local

**Comment by ripleymj** [comment]
Breaks running playbook via AWX, reverted in 1f984ed00eddcff71839eeaac7e030bf636c0d01

**Comment by kylelaker** [comment]
Does scripts/oem-build need to be updated to remove?

**Comment by ripleymj** [comment]
No, that's the way we're doing it. This attempted to move it into the yml file and simplify the command linel
